CREATE TABLE IF NOT EXISTS TESTPLAN (ID	SERIAL PRIMARY KEY, NAME VARCHAR(200) NOT NULL, OWNER VARCHAR(200));
CREATE TABLE IF NOT EXISTS TESTSCRIPT (ID SERIAL PRIMARY KEY, NAME VARCHAR(200), PLAN_ID INT REFERENCES TESTPLAN(ID));
CREATE TABLE IF NOT EXISTS TESTCASE (ID SERIAL PRIMARY KEY, NAME VARCHAR(200) NOT NULL, SCRIPT_ID INT references TESTSCRIPT(ID), STATUS VARCHAR(10));